### ISSUE TITLE
Generator for Boomerang using Yeoman?. 

### ISSUE THREAD

**Issue by vigneshshanmugam** [lognormal/boomerang#53]
Any thoughts?. 

Would solve lot of problems for new comers trying to make things work.

**Comment by bluesmoon** [comment]
I don't understand what this means. What do we need to generate?

**Comment by andreas-marschke** [comment]
If you plan to write a generator for writing plugins for boomerang, that'd actually be a neat idea. Otherwise it seems not like much that there is necessairly to do. Configuration of boomerang and it's integration into a project isn't something you can simply generate. 

For plugins there is a documented stub in the `plugins` directory and a wealth of existing examples with varying degrees of integration into projects it is used on.

**Comment by vigneshshanmugam** [comment]
@andreas-marschke Yeah I was thinking a boilerplate for plugins would be neat idea.

Also, For the new comers it would be better if we can give a yes/no type of UI for including plugins list using generator rather than using make script.

**Comment by bluesmoon** [comment]
@vigneshshanmugam we already have a boilerplate for plugins.  `plugins/plugins.js`

And an interactive method for creating a build is not automatable.  Right now all you have to do is:
```
make PLUGINS="plugins/rt.js plugins/navtiming.js"
```
This is easy to include in your project build scripts.

**Comment by vigneshshanmugam** [comment]
@bluesmoon Thanks for the clarification. Closing the issue.
